
---
- hosts: webnodes
  become: yes
  gather_facts: no
  vars:
    owner_ip: "{{ self_ip }}"
    other_ip: "{{ import_ip }}"
  tasks:
  - name: write the php main file
    template:
      src: index.php
      dest: /var/www/html/index.php
    notify:
    - restart apache
  - name: write the test config file
    template:
      src: index.html.j2
      dest: /var/www/html/index.html
    notify:
    - restart apache
  - name: Test Variables
    replace:
      path: /var/www/html/index.html
      regexp: 'other_ip_address'
      replace: "{{other_ip}}"
    notify:
    - restart nginx
  handlers:
    - name: restart apache
      service:
        name: apache2
        state: restarted